// flow-typed signature: c357f0911678910c3fe92dd69617ffd5
// flow-typed version: <<STUB>>/hole_vx.x.x/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hole'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hole' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hole/lib/hole-transform' {
  declare module.exports: any;
}

declare module 'hole/lib/index' {
  declare module.exports: any;
}

declare module 'hole/lib/main' {
  declare module.exports: any;
}

declare module 'hole/lib/transform' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hole/lib/hole-transform.js' {
  declare module.exports: $Exports<'hole/lib/hole-transform'>;
}
declare module 'hole/lib/index.js' {
  declare module.exports: $Exports<'hole/lib/index'>;
}
declare module 'hole/lib/main.js' {
  declare module.exports: $Exports<'hole/lib/main'>;
}
declare module 'hole/lib/transform.js' {
  declare module.exports: $Exports<'hole/lib/transform'>;
}
