// flow-typed signature: 97438d2e8ec28bf3e681f29841c4d94c
// flow-typed version: <<STUB>>/isomorphic-style-loader_vpiglovesyou/isomorphic-style-loader/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isomorphic-style-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'isomorphic-style-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'isomorphic-style-loader/src/index' {
  declare module.exports: any;
}

declare module 'isomorphic-style-loader/src/insertCss' {
  declare module.exports: any;
}

declare module 'isomorphic-style-loader/src/withStyles' {
  declare module.exports: any;
}

declare module 'isomorphic-style-loader/test/insertCss.spec' {
  declare module.exports: any;
}

declare module 'isomorphic-style-loader/test/withStyles.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'isomorphic-style-loader/src/index.js' {
  declare module.exports: $Exports<'isomorphic-style-loader/src/index'>;
}
declare module 'isomorphic-style-loader/src/insertCss.js' {
  declare module.exports: $Exports<'isomorphic-style-loader/src/insertCss'>;
}
declare module 'isomorphic-style-loader/src/withStyles.js' {
  declare module.exports: $Exports<'isomorphic-style-loader/src/withStyles'>;
}
declare module 'isomorphic-style-loader/test/insertCss.spec.js' {
  declare module.exports: $Exports<'isomorphic-style-loader/test/insertCss.spec'>;
}
declare module 'isomorphic-style-loader/test/withStyles.spec.js' {
  declare module.exports: $Exports<'isomorphic-style-loader/test/withStyles.spec'>;
}
