// flow-typed signature: 9fc4c8504e00772d6c3b2a3091476a30
// flow-typed version: <<STUB>>/isomorphic-style-loader--react-context_v^0.0.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isomorphic-style-loader--react-context'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'isomorphic-style-loader--react-context' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'isomorphic-style-loader--react-context/lib/index' {
  declare module.exports: any;
}

declare module 'isomorphic-style-loader--react-context/lib/insertCss' {
  declare module.exports: any;
}

declare module 'isomorphic-style-loader--react-context/lib/withStyles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'isomorphic-style-loader--react-context/lib/index.js' {
  declare module.exports: $Exports<'isomorphic-style-loader--react-context/lib/index'>;
}
declare module 'isomorphic-style-loader--react-context/lib/insertCss.js' {
  declare module.exports: $Exports<'isomorphic-style-loader--react-context/lib/insertCss'>;
}
declare module 'isomorphic-style-loader--react-context/lib/withStyles.js' {
  declare module.exports: $Exports<'isomorphic-style-loader--react-context/lib/withStyles'>;
}
